language: python
python: 3.5
sudo: required
dist: trusty
services: docker

env:
  global:
    secure: r2Wi5B2ELpx12Fea+euL1XrOa3LrE9+eNFm+FiYne49H+KorWER+AVqJuSOV6yViiHVAYYWLi5bHpCF2KTl2fxk9cFlRyocVuo2RGXK84Xj3XNNltBMyeutESRmsom1EGmTVcRs5D9XPRajPEgn6AC2HEdDg3dlFSVyvTix+wv03GhtVt+K20LuCqKsv8FwHj9PA5Tpcv1CcqIo1ekanhGkfaxAfVHxR4koA8Gs0dEC02csuhF0g4eMezMUrqH7tj80wqzcVWjcYyejVf4Vov5Fifc/upuo+bCEgbtaxVJyEDaA+D2HcWsIB5ckoA/WfRd3CBSC6zg1do1sSCP8wQaT9rPlrCxtydrSp+/8Uzfyom++yi3iPXCz1Q3gnCKMSFEro8R7di+ULSvu8OCIWxLvL6MjCV6Ti1gLBMnDTVhC5aO0DSUoAxj1U+UTDEv25v0dhXL5Md4Qy9/a1O5ekq2kj9/3NfTgcl2Y1FyVkKVbyE1SvekScU2WCd7qlm0PhRm4Ix1CKN3jTx2OpXuse7RR/r0dbpgCfTdMrEcQxoG6raWYU1xmjkfo8uO82xMniivntoyxgTwBl8PsiplkxwUGFlbhoBhc5BHdDBSAGBYiJuRkmxZ/EeOjAQPilKaXVXbDDwc9YqtgklcUbE99uByx50B9fkgJANNTD22ECuSE=

matrix:
  exclude:
    - python: 3.5
  include:
    - os: linux
      env: 
        - TOXENV=py35
        - MB_PYTHON_VERSION=3.5
    - os: osx
      language: objective-c
      env:
        - TOXENV=py35
        - MB_PYTHON_VERSION=3.5

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install
        
install:
  - pip install -U tox

script:
  - tox -e flake8
  - tox -e codecov
  - tox -e ${TOXENV}

before_deploy:
  - build_wheel . x86_64

deploy:
  provider: script
  script: deploy.sh
  true:
    condition: $TOXENV == py35
    repo: hredestig/python_boilerplate_decaf
    tags: true
